### ISSUE TITLE
error static assertion failed

### ISSUE THREAD

**Issue by wubw2017** [PJK/randomized-bsp-mincut#1]
During the building process， "static assertion failed" is reported in the AdjacencyListGraph.hpp. Please let me know, what am i doing wrong here ?

[  1%] [  3%] [  5%] [  7%] Building CXX object src/executables/CMakeFiles/karger_stein.dir/karger_stein.cpp.o
Building CXX object src/executables/CMakeFiles/complete_graph_generator.dir/complete_graph_generator.cpp.o
[  8%] [ 10%] Building CXX object src/executables/CMakeFiles/boost_stoer_wagner.dir/boost_stoer_wagner.cpp.o
Building CXX object src/executables/CMakeFiles/levine_transform.dir/levine_transform.cpp.o
[ 12%] [ 14%] Building CXX object src/executables/CMakeFiles/connectivity.dir/connectivity.cpp.o
Building CXX object src/executables/CMakeFiles/simple_generator.dir/simple_generator.cpp.o
Building CXX object src/executables/CMakeFiles/sorting_test.dir/sorting_test.cpp.o
Building CXX object src/executables/CMakeFiles/square_root.dir/square_root.cpp.o
Linking CXX executable levine_transform
[ 14%] Built target levine_transform
[ 16%] Building CXX object src/executables/CMakeFiles/square_root_project_gigaedge.dir/square_root_project_gigaedge.cpp.o
Linking CXX executable complete_graph_generator
Linking CXX executable simple_generator
[ 16%] Built target complete_graph_generator
[ 17%] [ 17%] Built target simple_generator
[ 19%] Building CXX object src/executables/CMakeFiles/transition.dir/transition.cpp.o
Building CXX object src/executables/CMakeFiles/transition.dir/__/SequentialKargerSteinCut.cpp.o
In file included from /home/superman/Desktop/MinimumCut/src/input/InputIterator.hpp:7:0,
                 from /home/superman/Desktop/MinimumCut/src/executables/karger_stein.cpp:1:
/home/superman/Desktop/MinimumCut/src/AdjacencyListGraph.hpp:56:2: error: static assertion failed: Expecting 4B unsigneds and 16B ulongs (else we are wasting space)
  static_assert(sizeof(Edge) == 16, "Expecting 4B unsigneds and 16B ulongs (else we are wasting space)");
  
In file included from /home/superman/Desktop/MinimumCut/src/MPIDatatype.hpp:4:0,
                 from /home/superman/Desktop/MinimumCut/src/executables/../sorting/SamplingSorter.hpp:11,
                 from /home/superman/Desktop/MinimumCut/src/executables/sorting_test.cpp:1:
/home/superman/Desktop/MinimumCut/src/AdjacencyListGraph.hpp:56:2: error: static assertion failed: Expecting 4B unsigneds and 16B ulongs (else we are wasting space)
  static_assert(sizeof(Edge) == 16, "Expecting 4B unsigneds and 16B ulongs (else we are wasting space)");
  
make[2]: *** [src/executables/CMakeFiles/connectivity.dir/connectivity.cpp.o] Error 1
make[1]: *** [src/executables/CMakeFiles/connectivity.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 21%] Building CXX object src/executables/CMakeFiles/transition.dir/__/MPIDatatype.cpp.o
make[2]: *** [src/executables/CMakeFiles/sorting_test.dir/sorting_test.cpp.o] Error 1
make[1]: *** [src/executables/CMakeFiles/sorting_test.dir/all] Error 2
[ 23%] Building CXX object src/executables/CMakeFiles/transition.dir/__/utils.cpp.o
make[2]: *** [src/executables/CMakeFiles/karger_stein.dir/karger_stein.cpp.o] Error 1
make[1]: *** [src/executables/CMakeFiles/karger_stein.dir/all] Error 2
[ 25%] Building CXX object src/executables/CMakeFiles/transition.dir/__/AdjacencyListGraph.cpp.o
make[2]: *** [src/executables/CMakeFiles/square_root.dir/square_root.cpp.o] Error 1
make[1]: *** [src/executables/CMakeFiles/square_root.dir/all] Error 2
[ 26%] Building CXX object src/executables/CMakeFiles/transition.dir/__/SquareRootCut.cpp.o
In file included from /home/superman/Desktop/MinimumCut/src/executables/../SquareRootCut.hpp:5:0,
                 from /home/superman/Desktop/MinimumCut/src/executables/square_root_project_gigaedge.cpp:1:
/home/superman/Desktop/MinimumCut/src/executables/../AdjacencyListGraph.hpp:56:2: error: static assertion failed: Expecting 4B unsigneds and 16B ulongs (else we are wasting space)
  static_assert(sizeof(Edge) == 16, "Expecting 4B unsigneds and 16B ulongs (else we are wasting space)");
  
In file included from /home/superman/Desktop/MinimumCut/src/input/InputIterator.hpp:7:0,
                 from /home/superman/Desktop/MinimumCut/src/executables/boost_stoer_wagner.cpp:1:
/home/superman/Desktop/MinimumCut/src/AdjacencyListGraph.hpp:56:2: error: static assertion failed: Expecting 4B unsigneds and 16B ulongs (else we are wasting space)
  static_assert(sizeof(Edge) == 16, "Expecting 4B unsigneds and 16B ulongs (else we are wasting space)");
  
/home/superman/Desktop/MinimumCut/src/SequentialKargerSteinCut.cpp: In member function ‘AdjacencyListGraph::Weight SequentialKargerSteinCut::compute()’:
/home/superman/Desktop/MinimumCut/src/SequentialKargerSteinCut.cpp:14:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (unsigned i { 0 }; i < m; i++) {
                                
In file included from /home/superman/Desktop/MinimumCut/src/AdjacencyListGraph.cpp:1:0:
/home/superman/Desktop/MinimumCut/src/AdjacencyListGraph.hpp:56:2: error: static assertion failed: Expecting 4B unsigneds and 16B ulongs (else we are wasting space)
  static_assert(sizeof(Edge) == 16, "Expecting 4B unsigneds and 16B ulongs (else we are wasting space)");
  
make[2]: *** [src/executables/CMakeFiles/transition.dir/__/AdjacencyListGraph.cpp.o] Error 1
In file included from /home/superman/Desktop/MinimumCut/src/SequentialSquareRootCut.hpp:4:0,
                 from /home/superman/Desktop/MinimumCut/src/SequentialSquareRootCut.cpp:1:
/home/superman/Desktop/MinimumCut/src/AdjacencyListGraph.hpp:56:2: error: static assertion failed: Expecting 4B unsigneds and 16B ulongs (else we are wasting space)
  static_assert(sizeof(Edge) == 16, "Expecting 4B unsigneds and 16B ulongs (else we are wasting space)");
  
In file included from /home/superman/Desktop/MinimumCut/src/input/InputIterator.hpp:7:0,
                 from /home/superman/Desktop/MinimumCut/src/input/InputIterator.cpp:1:
/home/superman/Desktop/MinimumCut/src/AdjacencyListGraph.hpp:56:2: error: static assertion failed: Expecting 4B unsigneds and 16B ulongs (else we are wasting space)
  static_assert(sizeof(Edge) == 16, "Expecting 4B unsigneds and 16B ulongs (else we are wasting space)");

**Comment by PJK** [comment]
Hi @wubw2017, and sorry for the tardy response. No fault of yours -- because of performance reasons, we expect the architecture to have 32 bit unsigned ints. You should be fine just removing that assertion, but I suggest that you have a look at https://github.com/PJK/comm-avoiding-cuts-cc instead -- it implements a very similar algorithm and is also faster and much more mature.
